name: Release

on:
    create:
        tags:
            - v*

jobs:
    release:
        runs-on: ubuntu-latest
        env:
            CI: 'true'
        steps:
            - 
                name: Set up Node
                uses: actions/setup-node@v1
                with:
                    node-version: 14
            - 
                name: Check out code
                uses: actions/checkout@v2
                with:
                    fetch-depth: 50
            - 
                id: cache
                name: Cache node_modules
                uses: actions/cache@v1
                with:
                    path: node_modules
                    key: node_modules-${{ runner.OS }}-${{ hashFiles('package-lock.json') }}
            - 
                run: touch node_modules
                if: steps.cache.outputs.cache-hit == 'true'

            - 
                name: Install dependencies
                run: npm ci

            - 
                name: Publish to Visual Studio Marketplace
                    run: npx semantic-release
                    env:
                        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

            -
                name: Post-release sync
                run: ./scripts/ci/sync.bash
                if: success()